config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'user_sessions#new'
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'

  get '/draw', to: 'knitting_diagrams#new'
  post '/draw', to: 'knitting_diagrams#create'
  get '/draws', to: 'knitting_diagrams#index'
  get '/privacy', to: 'top#privacy'
  get '/service', to: 'top#service'
  root 'top#index'
  resources :posts do
    collection do
      get :favorites
    end
    get 'search', on: :collection
  end
  resources :users, param: :public_uid, only: %i[new create show]
  resources :favorites, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence:true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/knitting_diagram.rb
class KnittingDiagram < ApplicationRecord

  validates :square_outer, presence:true
  validates :square_center, presence:true
  validates :square_inner, presence:true

  belongs_to :user
end

app/models/mood.rb
class Mood < ApplicationRecord
  has_many :posts

  validates :name, presence:true

end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :post_image, PostImageUploader
  belongs_to :user
  belongs_to :category
  belongs_to :mood

  has_many :favorites

  validates :finished_at, presence:true
  scope :by_category, ->(category_id) { where(category_id: category_id) }
  scope :by_mood, ->(mood_id) { where(mood_id: mood_id) }
  
  def split_id_from_youtube_url
    youtube_url.split('/').last if youtube_url.present?
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  generate_public_uid

  validates :name, presence:true
  validates :email, presence:true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :knitting_diagrams, dependent: :destroy

  def to_param
    public_uid
  end

  def favorite(post)
    favorite_posts << post
  end

  def unfavorite(post)
    favorite_posts.destroy(post)
  end

  def favorite?(post)
    favorite_posts.include?(post)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  add_flash_types :success, :info, :warning, :danger

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    current_user.favorite(@post)
  end

  def destroy
    @post = current_user.favorites.find(params[:id]).post
    current_user.unfavorite(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :login_required, only: %i[new create edit]

  def index
    @posts = Post.all
    @search_posts_form = SearchPostsForm.new(search_params)
    @posts = @search_posts_form.search.order(id: :desc).page(params[:page]).per(4)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @moods = Mood.all
    @categories = Category.all
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @moods = Mood.all
    @categories = Category.all
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to post_path(post), success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path, info: t('.info') 
  end

  def favorites
    @favorite_posts = current_user.favorite_posts.includes(:user).order(created_at: :desc).page(params[:page]).per(4)
  end

  private

  def search_params
    params[:q]&.permit(:category_id, :mood_id)
  end

  def post_params
    params.require(:post).permit(:body, :category_id, :mood_id, :post_image, :post_image_cache, :finished_at, :youtube_url).merge(user_id: current_user.id)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :login_required, only: %i[show]

  def index;end

  def service;end

  def privacy;end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new;end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, info: t('.info')
  end

  private

  def session_params
    params.permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    set_user
    @posts = Post.where(user_id: current_user.id).includes(:user).order("created_at DESC").page(params[:page]).per(4)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def edit;end

  private

  def set_user
    @user = User.find_by(public_uid: params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :public_uid)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/knitting_diagrams_helper.rb
module KnittingDiagramsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrochetWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

  </head>

  <body>
    <%= render 'shared/flash_message' %>
    <% if current_user %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header class="header bg-green-200">
  <nav class="border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800 my-auto ">
    <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
      <%= link_to root_path, class: 'flex' do %>
        <%= image_tag src='logo.png', class: 'mr-3 sm:h-9 h-6'%>
        <span class="text-xl text-green-900 whitespace-nowrap font-body">FOR CROCHET</span>
      <%end%>
      <div class="flex items-center lg:order-2">
        <%= link_to login_path do%>
          <button class="flex font-body text-gray-800 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-2 lg:px-5 py-2 lg:py-2.5 mr-2 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800">
            ログイン
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
            </svg>
          </button>
        <% end %>
        <%= link_to new_user_path, method: :get do%>
          <div class="font-body text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-2 lg:px-5 py-2 lg:py-2.5 mr-2 dark:bg-green-600 dark:hover:bg-green-700 focus:outline-none dark:focus:ring-green-800">
            会員登録
          </div>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_embed_youtube.html.erb
<%= content_tag 'iframe', nil, src: "https://www.youtube.com/embed/#{@post.split_id_from_youtube_url}", frameborder: 0, allow: 'autoplay', allow: 'encrypted-media', allowfullscreen: true %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'success' %>
    <div class="bg-green-100 border border-green-400 text-green-700 font-body px-4 py-3 mt-16 rounded relative">
      <svg aria-hidden="true" class="inline flex-shrink-0 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
      <strong class="font-bold"><%= message %></strong>
    </div>
  <% elsif message_type == 'info' %>
    <div class="text-gray-700 bg-gray-200 dark:bg-gray-700 dark:text-gray-300 font-body px-4 py-3 mt-16 rounded relative">
      <svg aria-hidden="true" class="inline flex-shrink-0 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
      <strong class="font-bold"><%= message %></strong>
    </div>
  <% elsif message_type == 'danger' %>
    <div class="flex text-red-700 bg-red-100 rounded-lg dark:bg-red-200 dark:text-red-800 font-body px-4 py-3 mt-16 rounded relative">
      <svg aria-hidden="true" class="inline flex-shrink-0 mr-3 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
      <span class="sr-only">Info</span>
      <strong class="font-bold"><%= message %></strong>
    </div>
  <% elsif message_type == 'warning' %>
    <div class="text-yellow-700 bg-yellow-100 rounded-lg p-4 mb-4"><%= message %></div>
  <% else %>
    <div class="text-blue-700 bg-blue-100 rounded-lg p-4 mb-4"><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-gray-600 font-body container px-5 py-24 mx-auto">
  <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
    <%= link_to root_path, class: 'flex' do %>
      <%= image_tag src='logo.png', class: 'mr-3 sm:h-9 h-6'%>
      <span class="text-xl text-green-900 whitespace-nowrap font-body">FOR CROCHET</span>
    <%end%>
    <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">© 2022 color imagine FOR CROCHET  —
      @rikako
    </p>
    <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
      <%= link_to "利用規約", service_path, class: 'text-gray-500'%>
      <%= link_to "プライバシーポリシー", privacy_path, class: 'ml-3 text-gray-500' %>
    </span>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header bg-green-200">
  <nav class="border-green-200 px-4 lg:px-6 py-2.5 dark:bg-green-800 my-auto bg-green-200">
    <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
      <%= link_to root_path, class: 'flex' do %>
        <%= image_tag src='logo.png', class: 'mr-3 sm:h-9 h-6'%>
        <span class="text-xl text-green-900 whitespace-nowrap font-body">FOR CROCHET</span>
      <%end%>
      <div class="flex items-center lg:order-2">
        <%= link_to logout_path, method: :delete do%>
          <button class="flex font-body text-gray-800 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800">
            ログアウト
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
            </svg>
          </button>
        <% end %>
        <button data-collapse-toggle="mobile-menu-2" type="button" class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg lg:hidden hover:bg-green-100 focus:outline-none focus:ring-2 focus:ring-green-200 dark:text-green-400 dark:hover:bg-green-700 dark:focus:ring-green-600" aria-controls="mobile-menu-2" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
          <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
      </div>
        
        <div class="hidden justify-between items-center w-full lg:flex lg:w-auto lg:order-1" id="mobile-menu-2">
          <div class="flex flex-col mt-4 lg:flex-row lg:space-x-8 lg:mt-0 font-body">
            <button id="dropdownDefault" data-dropdown-toggle="dropdown" class="flex block py-2 pr-4 pl-3 text-green-700 border-b border-green-100 hover:bg-green-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-green-700 lg:p-0 dark:text-green-400 lg:dark:hover:text-green-100 dark:hover:bg-green-700 dark:hover:text-green-100 lg:dark:hover:bg-transparent dark:border-green-700" type="button">
              <div>マイページ</div>
              <svg class="ml-2 mt-1 w-4 h-4" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg>
            </button>
            <div id="dropdown" class="hidden font-body z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 block" data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="bottom" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(327px, 70px, 0px);">
              <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefault">
                <li>
                  <%= link_to user_path(current_user.public_uid) do%>
                    <div class="flex block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4" />
                      </svg>
                      <div class="ml-4">
                        <p class="text-gray-900">投稿を編集する</p>
                      </div>
                    </div>
                  <% end %>
                </li>
                <li>
                  <%= link_to ("/posts/new") do %>
                    <div class="flex block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                      </svg>
                      <div class="ml-4">
                        <p class="text-gray-900">投稿する</p>
                      </div>
                    </div>
                  <% end %>
                </li>
                <li>
                  <%= link_to ("/posts") do %>
                    <div class="flex block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M8 16l2.879-2.879m0 0a3 3 0 104.243-4.242 3 3 0 00-4.243 4.242zM21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                      <div class="ml-4">
                        <p class="text-gray-900">みんなの投稿を見る</p>
                      </div>
                    </div>
                  <% end %>
                </li>
                <li>
                  <%= link_to ("/draw") do %>
                    <div class="flex block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01" />
                      </svg>
                      <div class="ml-4">
                        <p class="text-gray-900">色を塗る</p>
                      </div>
                    </div>
                  <% end %>
                </li>
              </ul>
            </div>
            <%= link_to favorites_posts_path do%>
              <div class="block py-2 pr-4 pl-3 text-green-700 border-b border-green-100 hover:bg-green-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-green-700 lg:p-0 dark:text-green-400 lg:dark:hover:text-green-100 dark:hover:bg-green-700 dark:hover:text-green-100 lg:dark:hover:bg-transparent dark:border-green-700">
                お気に入り
              </div>
            <% end %>
            <%= link_to draws_path do%>
              <div class="block py-2 pr-4 pl-3 text-green-700 border-b border-green-100 hover:bg-green-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-green-700 lg:p-0 dark:text-green-400 lg:dark:hover:text-green-100 dark:hover:bg-green-700 dark:hover:text-green-100 lg:dark:hover:bg-transparent dark:border-green-700">
                塗ったカラーイメージ
              </div>
            <% end %>
          </div>
        </div>
    </div>
  </nav>
</header>
<script src="https://unpkg.com/flowbite@1.4.7/dist/flowbite.js"></script>