config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'user_sessions#new'
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'

  get '/draw', to: 'knitting_diagrams#new'
  post '/draw', to: 'knitting_diagrams#create'
  get '/draws', to: 'knitting_diagrams#index'
  get '/privacy', to: 'top#privacy'
  get '/service', to: 'top#service'
  root 'top#index'
  resources :posts do
    collection do
      get :favorites
    end
    get 'search', on: :collection
  end
  resources :users, param: :public_uid, only: %i[new create show]
  resources :favorites, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence:true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/knitting_diagram.rb
class KnittingDiagram < ApplicationRecord

  validates :square_outer, presence:true
  validates :square_center, presence:true
  validates :square_inner, presence:true

  belongs_to :user
end

app/models/mood.rb
class Mood < ApplicationRecord
  has_many :posts

  validates :name, presence:true

end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :post_image, PostImageUploader
  belongs_to :user
  belongs_to :category
  belongs_to :mood

  has_many :favorites

  validates :finished_at, presence:true
  scope :by_category, ->(category_id) { where(category_id: category_id) }
  scope :by_mood, ->(mood_id) { where(mood_id: mood_id) }
  
  def split_id_from_youtube_url
    youtube_url.split('/').last if youtube_url.present?
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  generate_public_uid

  validates :name, presence:true
  validates :email, presence:true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :knitting_diagrams, dependent: :destroy

  def to_param
    public_uid
  end

  def favorite(post)
    favorite_posts << post
  end

  def unfavorite(post)
    favorite_posts.destroy(post)
  end

  def favorite?(post)
    favorite_posts.include?(post)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  add_flash_types :success, :info, :warning, :danger

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    current_user.favorite(@post)
  end

  def destroy
    @post = current_user.favorites.find(params[:id]).post
    current_user.unfavorite(@post)
  end
end

app/controllers/knitting_diagrams_controller.rb
class KnittingDiagramsController < ApplicationController
  before_action :login_required, only: %i[create index]

  def index
    @knitting_diagrams = KnittingDiagram.all.where(user_id: current_user.id).includes(:user).order("created_at DESC").page(params[:page]).per(3)
  end

  def new
    @knitting_diagrams = KnittingDiagram.new
  end

  def create
    @knitting_diagrams = current_user.knitting_diagrams.new(knitting_diagram_params)
    @knitting_diagrams.save
    redirect_to draws_path, success: t('.success')
  end

  private

  def knitting_diagram_params
    params.permit(:square_outer, :square_center, :square_inner, :user_id, :user_name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :login_required, only: %i[new create edit]

  def index
    @posts = Post.all
    @search_posts_form = SearchPostsForm.new(search_params)
    @posts = @search_posts_form.search.order(id: :desc).page(params[:page]).per(4)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @moods = Mood.all
    @categories = Category.all
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @moods = Mood.all
    @categories = Category.all
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to post_path(post), success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path, info: t('.info') 
  end

  def favorites
    @favorite_posts = current_user.favorite_posts.includes(:user).order(created_at: :desc).page(params[:page]).per(4)
  end

  private

  def search_params
    params[:q]&.permit(:category_id, :mood_id)
  end

  def post_params
    params.require(:post).permit(:body, :category_id, :mood_id, :post_image, :post_image_cache, :finished_at, :youtube_url).merge(user_id: current_user.id)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :login_required, only: %i[show]

  def index;end

  def service;end

  def privacy;end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new;end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, info: t('.info')
  end

  private

  def session_params
    params.permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    set_user
    @posts = Post.where(user_id: current_user.id).includes(:user).order("created_at DESC").page(params[:page]).per(4)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def edit;end

  private

  def set_user
    @user = User.find_by(public_uid: params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :public_uid)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/knitting_diagrams_helper.rb
module KnittingDiagramsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.js.erb
$("#js-favorite-button-for-post-<%= @post.id %>").replaceWith("<%= j(render('posts/unfavorite', post: @post)) %>");

app/views/favorites/destroy.js.erb
$("#js-favorite-button-for-post-<%= @post.id %>").replaceWith("<%= j(render('posts/favorite', post: @post)) %>");

app/views/knitting_diagrams/create.html.erb
<div>
  <h1 class="font-bold text-4xl">KnittingDiagrams#create</h1>
  <p>Find me in app/views/knitting_diagrams/create.html.erb</p>
</div>

app/views/knitting_diagrams/index.html.erb
<div class="container px-5 py-24 mx-auto"> 
  <div class="flex flex-col text-center w-full mb-10 bg-yellow-100">
    <%= image_tag "flower1.png"%>
    <h1 class="text-3xl font-medium title-font mb-4 text-gray-900 font-body">Drawing Knitting diagrams</h1>
    <p class="lg:w-2/3 mx-auto leading-relaxed text-base font-body text-lg">たくさん編み図の配色を保存して、比べてみて出来上がるのを想像してみてください🌼</p>
    <%= image_tag "flower1.png"%>
  </div>
  <div class="container mx-auto mt-6">
    <% if @knitting_diagrams.present? %>
      <section class="flex flex-wrap justify-around">
        <% @knitting_diagrams.each do |knitting_diagram|%>
          <div id="knitting_diagrams-id-<%= knitting_diagram.id%>" class="flex flex-wrap justify-around mx-3 mb-3 object-cover">
            <div class= "square_outer1" style="background-color:<%= knitting_diagram.square_outer %>"></div>
            <div class= "square_center2 m-12" style="background-color:<%= knitting_diagram.square_center %>"></div>
            <div class= "square_inner3 m-24" style="background-color:<%= knitting_diagram.square_inner %>"></div>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="justify-center mx-auto">
        <div class= "text-center text-green-500 font-body lg:text-3xl mt-11 mx-auto leading-normal"><%= t('.no_result') %><br>編み図に似せて色を塗って配色を考えてみませんか🌷</div>
        <button class=" text-green-500 font-body rounded px-4 py-2 mt-11 shadow-2xl w-full lg:text-2xl"><%= link_to "塗りにいく>>", draw_path %></button>
      </div>
    <% end %>
    <%= paginate @knitting_diagrams, window: 2 %>
  </div>
</div>

app/views/knitting_diagrams/new.html.erb
<div class="container px-5 py-24 mx-auto">
  <div class="flex flex-col text-center w-full mb-10 bg-pink-100">
    <%= image_tag "flower2.png"%>
    <h1 class="text-3xl font-medium title-font mb-4 text-gray-900 font-body ">Let's drawing Knitting diagrams</h1>
    <p class="lg:w-2/3 mx-auto leading-relaxed text-base font-body text-lg">編み図を図形に例えました。<br>さまざまな色をクリックでイメージできます🌼</p>
    <%= image_tag "flower2.png"%>
  </div>

  <section class="text-gray-600 body-font flex justify-center text-center">
    <div>
      <%= form_with model: @knitting_diagram, local: true do |f| %>
        <div class="lg:w-full flex flex-wrap font-body">
          <div class="flex flex-shrink-0 rounded-lg object-cover object-center mb-4 mt-10 justify-around lg:pl-10 lg:py-6 my-auto">
            <%= f.color_field :square_outer, {class: 'square_outer'} %>
            <%= f.color_field :square_center, {class: 'square_center mt-12'} %>
            <%= f.color_field :square_inner, {class: 'square_inner mt-24'} %>
          </div>
					<% if current_user %>
            <div class="flex p-2 justify-center lg:pl-10 mx-auto my-auto">
              <button type= "submit">
                <%= f.submit (t '.submit'), class: 'w-36 h-36 bg-yellow-300 p-2 rounded-full hover:bg-yellow-400 text-white font-semibold' %>
              </button>
            </div>
          <% else %>
            <div class="p-2 justify-center lg:pl-10 mx-auto my-auto">
              <div class="p-2 justify-center space-x-16">
                <%= link_to new_user_path do %>
                  <button class="w-36 h-36 bg-red-300 p-2 rounded-full hover:bg-red-400 text-white font-semibold">
                    会員登録はこちら
                  </button>
                <% end %>
              </div>
              <p class="text-green-500 lg:text-xl mb-10 mt-3 justify-cente">※マイページに保存する場合会員登録が必要です。</p>
            </div>
          <% end %>
        </div>
      <%end%>
    </div>
  </section>
  <%= javascript_pack_tag 'knitting_diagram/new' %>
</div>

app/views/posts/_favorite.html.erb
<%= link_to favorites_path(post_id: post.id),
            id: "js-favorite-button-for-post-#{post.id}",
            class:"float-right",
            method: :post,
            remote: true do %>
  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
    <path stroke-linecap="round" stroke-linejoin="round" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
  </svg>
<% end %>

app/views/posts/_favorite_button.html.erb
<% if current_user.favorite?(post) %>
  <%= render 'unfavorite', { post: post } %>
<% else %>
  <%= render 'favorite', { post: post } %>
<% end %>

app/views/posts/_post.html.erb
<section class="lg:w-1/4 text-gray-600 body-font">
  <div class="container px-5 py-12 mx-auto">
    <div class="flex flex-wrap -m-4">
      <div class="p-4  w-full">
				<div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
					<%= link_to post_path(post) do %>
						<%= image_tag post.post_image_url, class: 'lg:h-80 md:h-36 w-full object-cover object-center'%>
					<%	end %>
					<div class="p-6">
						<div class="flex">
							<div class="text-lg font-medium text-gray-900 mb-3 mr-3 font-body" id="post-id-<%= post.id %>">
								<%= "#{post.user.name}さんの作品"%>
							</div>
							<span class="rounded-lg bg-green-500 px-4 py-2 mr-3 inline-flex lg:ml-auto md:ml-0 ml-auto leading-none text-sm">
									<% if current_user %>
										<%= render 'favorite_button', post: post %>
									<% else %>
										<%= link_to login_path method: :post do %>
											<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
												<path stroke-linecap="round" stroke-linejoin="round" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
											</svg>
										<%end%>
									<%end%>
							<span>
						</div>
						<div class="flex items-center flex-wrap ">
							<%= link_to post_path(post), class: 'text-green-500 inline-flex items-center md:mb-2 lg:mb-0 font-body' do%>
								詳しく見る
								<svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
									<path d="M5 12h14"></path>
									<path d="M12 5l7 7-7 7"></path>
								</svg>
							<% end %>
						</div>
					</div>
				</div>
      </div>
    </div>
  </div>
</section> 

app/views/posts/_unfavorite.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(post_id: post.id)), id: "js-favorite-button-for-post-#{post.id}", class:"float-right", method: :delete, remote: true, data: {"turbolinks" => false} do %>
  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-yellow-300" viewBox="0 0 20 20" fill="currentColor">
    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM7 9a1 1 0 100-2 1 1 0 000 2zm7-1a1 1 0 11-2 0 1 1 0 012 0zm-.464 5.535a1 1 0 10-1.415-1.414 3 3 0 01-4.242 0 1 1 0 00-1.415 1.414 5 5 0 007.072 0z" clip-rule="evenodd" />
  </svg>
<% end %>

app/views/posts/edit.html.erb
<div class="container px-5 py-24 mx-auto">
  <div class="flex flex-col w-full mb-15 bg-pink-100">
    <%= image_tag "flower2.png"%>
    <h1 class="text-3xl font-medium title-font mb-4 text-gray-900 font-body text-center">Editing your post</h1>
    <%= image_tag "flower2.png"%>
  </div>

  <section class="text-gray-600 body-font overflow-hidden">
    <div class= "justify-center">
      <%= form_with model: @post, url: post_path(@post), local: true do |f| %>
        <div class="lg:w-full mx-auto flex flex-wrap">
          <div class="form-group lg:w-1/2 w-full lg:pl-10 lg:py-6 my-auto lg:flex">
            <%= f.hidden_field :post_image_cache %>
            <%= image_tag @post.post_image_url, class: 'shadow-2xl rounded-lg lg:mr-3 lg:w-1/2 lg:h-1/2 md:h-36 object-cover object-center'%>
            <div class='shadow-2xl rounded-lg lg:w-1/2 lg:h-1/2 md:h-36 lg:ml-3 object-cover object-center' id= 'preview' size= '100x100'></div>
          </div>
          <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 my-auto font-body">
            <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
              <%= f.label :post_image, t('.post_image'), class: 'text-gray-600 h-10 pr-10 bg-white font-body' %>
              <%= f.file_field :post_image, onChange: "imgPreView(event)", class: 'text-sm text-gray-500'%>
              <div class="form-group inline-block mt-3">
                <%= f.label :category_id, 'カテゴリ' %>
                <div class="border border-gray-300 rounded-full text-gray-600 h-10 pl-5 pr-10 bg-white hover:border-gray-400 focus:outline-none appearance-none font-body">
                  <%= f.collection_select :category_id, @categories, :id, :name, { include_blank: '選択してください'}, { class: 'form-control py-1' , required: true } %>
                </div>
              </div>
              <div class="form-group inline-block mt-3">
                <%= f.label :mood_id, 'イメージ' %>
                <div class="border border-gray-300 rounded-full text-gray-600 h-10 pl-5 pr-10 bg-white hover:border-gray-400 focus:outline-none appearance-none font-body">
                  <%= f.collection_select :mood_id, @moods, :id, :name, { include_blank: '選択してください'}, { class: 'form-control py-1' , required: true } %>
                </div>
              </div>

              <div class="form-group inline-block mt-3">
                <%= f.label :finished_at, "作品にかかった時間はどのくらいですか？" %>
                <%= f.text_field :finished_at, placeholder: "(例)およそ1日", class: 'inline-flex border border-gray-300 rounded-full text-gray-600 h-10 pl-5 pr-10 bg-white hover:border-gray-400 focus:outline-none appearance-none font-body', required: true%>
              </div>

              <div class="form-group inline-block mt-3">
                <%= f.label :youtube_url, "参考にしたYoutubeはありますか？(任意)"%>
                <%= f.text_field :youtube_url, class: 'inline-flex border border-gray-300 rounded-full text-gray-600 h-10 pl-5 pr-10 bg-white hover:border-gray-400 focus:outline-none appearance-none font-body'%>
              </div>

              <div class="form-group inline-block mt-3">
                <%= f.label :body, "糸の太さなどわかったら教えてください(任意)" %>
                <%= f.text_area :body, placeholder: "(例)8号を使用しました!初心者の私でも簡単に編むことができました！", class: 'w-full bg-white rounded-lg border border-gray-300 focus:border-green-500 focus:ring-2 focus:ring-green-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out"' %>
              </div>
              <div class="flex mt-3">
                <%= f.submit class: 'flex ml-auto text-gray-700 bg-pink-200 border-0 py-2 px-6 focus:outline-none hover:bg-pink-500 rounded' %>
              </div>
          </div>
        </div>
      <%end%>
    </div>
  </section>
</div>
<script>
  function imgPreView(event) {
  var file = event.target.files[0];
  var reader = new FileReader();
  var preview = document.getElementById("preview");
  var previewImage = document.getElementById("previewImage");

  if(previewImage != null) {
    preview.removeChild(previewImage);
  }
  reader.onload = function(event) {
    var img = document.createElement("img");
    img.setAttribute("src", reader.result);
    img.setAttribute("id", "previewImage");
    preview.appendChild(img);
  };

  reader.readAsDataURL(file);
  }
</script>

app/views/posts/favorites.html.erb
<div class="container px-5 py-24 mx-auto">
  <div class="flex flex-col text-center w-full mb-10 bg-yellow-100">
    <%= image_tag "flower1.png"%>
    <h1 class="text-3xl font-medium title-font mb-4 text-gray-900 font-body ">Favorite works</h1>
    <p class="lg:w-2/3 mx-auto leading-relaxed text-base font-body text-lg">お気に入りのかぎ針で編んだ作品の一覧です。<br>自分の投稿と他の皆さんの作品をお気に入りしてアイデアを合わせるのもいいですね🌼</p>
    <%= image_tag "flower1.png"%>
  </div>
  <div>
    <div class="flex justify-center flex-wrap">
      <% if @favorite_posts.present? %>
        <%= render @favorite_posts %>
      <% else %>
        <div class= "text-center text-green-500 font-body lg:text-3xl mt-11 leading-normal"><%= t('.no_result') %><br><%= link_to "投稿一覧", posts_path, class: "bg-yellow-100 shadow-lg px-4 mt-11"%>でお気に入りの作品を見つけてみませんか🌷</div>
      <% end %>
    </div>
    <%= paginate @favorite_posts, window: 2 %>
  </div>
</div>

app/views/user_sessions/new.html.erb
<section class="flex flex-col md:flex-row h-screen items-center">

  <div class="bg-green-600 hidden lg:block w-full md:w-1/2 xl:w-2/3 h-screen">
    <%= image_tag "knitting1.jpg", class: "w-full h-full"%>
  </div>

  <div class="bg-white w-full md:max-w-md lg:max-w-full md:mx-auto md:mx-0 md:w-1/2 xl:w-1/3 h-screen px-6 lg:px-16 xl:px-12 flex items-center justify-center">

    <div class="w-full h-100">

      <h1 class="text-xl md:text-2xl font-bold leading-tight mt-12 font-body text-center"><%= t('.title') %></h1>

      <%= form_with url: login_path, local: true do |f| %>
        <div>
          <%= f.label :email , User.human_attribute_name(:email), class: 'block text-gray-700 font-body' %>
          <%= f.email_field :email, class: 'font-body form-control w-full px-4 py-3 rounded-lg bg-gray-200 mt-2 border focus:border-green-500 focus:bg-white focus:outline-none' %>
        </div>

        <div class="mt-4">
          <%= f.label :password , User.human_attribute_name(:password), class: 'block text-gray-700 font-body' %>
          <%= f.password_field :password, class: 'font-body form-control w-full px-4 py-3 rounded-lg bg-gray-200 mt-2 border focus:border-green-500 focus:bg-white focus:outline-none' %>
        </div>

        <button type="submit" class="w-full block bg-green-500 hover:bg-green-400 focus:bg-green-400 text-white font-semibold rounded-lg px-4 py-3 mt-6 font-body"><%= t('.title') %>する>></button>
      <% end %>
        <div class="text-right mt-11 text-sm font-semibold text-gray-700 font-body">
          <%= link_to "会員登録お済みでないようでしたらこちらから🌼", new_user_path, method: :get, class: 'hover:bg-green-300 py-3 px-3 rounded-full'%>
        </div>
    </div>
  </div>

</section>

app/views/users/show.html.erb
<div class="container px-5 py-24 mx-auto">
  <div class="flex flex-col text-center w-full mb-10 bg-yellow-100">
    <%= image_tag "flower1.png"%>
    <h1 class="lg:text-3xl text-xl title-font mb-4 text-gray-900 font-body"><%= "#{current_user.name}さん、何を作りますか？" %></h1>
    <p class="lg:w-2/3 mx-auto leading-relaxed text-sm font-body lg:text-lg">かぎ針で編んだ作品をコレクションしましょう!</p>
    <%= image_tag "flower1.png"%>
  </div>
  <div class="mx-auto">
    <p class="text-center text-green-500 lg:text-3xl text-xl mt-11 font-body"><%= "🌼#{current_user.name}さんが投稿した作品一覧🌼" %></p>
    <div class="flex justify-center flex-wrap">
      <% if @posts.present? %>
        <% @posts.each do |post| %>
        <section class="lg:w-1/4 w-full text-gray-600 body-font">
          <div class="container px-5 py-12 mx-auto">
            <div class="flex flex-wrap -m-4">
              <div class="p-4 w-full">
                <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
                  <%= image_tag post.post_image_url, class: 'lg:h-80 md:h-36 w-full object-cover object-center'%>
                  <div class="p-6 font-body">
                    <div class="text-sm text-gray-900 mb-3 mr-3" id="post-id-<%= post.id %>">
                      <%= "#{post.body}"%>
                    </div>
                    <div class="flex items-center flex-wrap ">
                      <%= link_to edit_post_path(post), class: 'text-green-500 inline-flex items-center md:mb-2 lg:mb-0 font-body' do%>
                        編集する
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                        </svg>
                      <% end %>
                      <%= link_to '削除する', post, method: :delete, data: { confirm: "投稿を削除してよろしいですか？"}, class: 'font-body w-2/5 text-center sm:w-auto px-5 py-2 ml-20 text-sm font-medium focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-gray-900 focus:outline-none transition-colors duration-200 rounded-full block bg-transparent hover:bg-red-700 border border-red-700 text-red-700 hover:text-red-200'%>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section> 
        <% end %>
      <% else %>
        <p class="text-center text-green-500 font-body lg:text-3xl mt-11 leading-normal"> 投稿していません。<br><%="#{current_user.name}さんの編み物をぜひみたいです🌷" %></p>
      <% end %>
    </div>
    <%= paginate @posts, window: 2 %>
  </div>
</div>